[tox]
envlist = py38, py39, py310, py311, lint, security
skip_missing_interpreters = true

[testenv]
deps = -rrequirements-test.txt
commands =
    pytest {posargs}
setenv =
    PYTHONPATH = {toxinidir}

[testenv:lint]
deps =
    black>=23.0.0
    isort>=5.12.0
    flake8>=6.0.0
    pylint>=2.17.0
commands =
    black --check --diff custom_components tests
    isort --check-only --diff custom_components tests
    flake8 custom_components tests
    pylint custom_components tests

[testenv:security]
deps =
    bandit>=1.7.0
commands =
    bandit -r custom_components -c .github/bandit.yaml

[testenv:coverage]
deps =
    -rrequirements-test.txt
    coverage>=7.0.0
commands =
    pytest --cov=custom_components.portainer --cov-report=term-missing --cov-report=html --cov-report=xml --cov-fail-under=80

[testenv:format]
deps =
    black>=23.0.0
    isort>=5.12.0
commands =
    black custom_components tests
    isort custom_components tests

[flake8]
ignore = W293
max-line-length = 220
max-complexity = 10
exclude = ./.git,
          ./tests,
          ./.github,
          __pycache__,
          ./docs,

[pylint]
disable = duplicate-code,
          too-many-public-methods,
          useless-return,
          import-error,
          too-many-arguments,
          too-many-instance-attributes,
          simplifiable-if-expression,
          bare-except