"""Definitions for sensor entities."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.helpers.entity import EntityCategory

from .const import CUSTOM_ATTRIBUTE_ARRAY


DEVICE_ATTRIBUTES_ENDPOINTS = [
    "Type",
    "Status",
    "DockerVersion",
    "Swarm",
    "TotalCPU",
    "TotalMemory",
    "RunningContainerCount",
    "StoppedContainerCount",
    "HealthyContainerCount",
    "UnhealthyContainerCount",
    "VolumeCount",
    "ImageCount",
    "ServiceCount",
    "StackCount",
]

DEVICE_ATTRIBUTES_CONTAINERS = [
    "Image",
    "Network",
    "Compose_Stack",
    "Compose_Service",
    "Compose_Version",
    "Environment",
    # add all attributes form CUSTOM_ATTRIBUTE_ARRAY
    CUSTOM_ATTRIBUTE_ARRAY,
]


@dataclass(kw_only=True)
class PortainerSensorEntityDescription(SensorEntityDescription):
    """Class describing portainer entities."""

    ha_group: str | None = None
    ha_connection: str | None = None
    ha_connection_value: str | None = None
    data_path: str | None = None
    data_attribute: str | None = None
    data_name: str | None = None
    data_uid: str | None = None
    data_reference: str | None = None
    supported_states: list[str] | None = None
    data_attributes_list: List = field(default_factory=lambda: [])
    func: str = "PortainerSensor"


SENSOR_TYPES: tuple[PortainerSensorEntityDescription, ...] = (
    PortainerSensorEntityDescription(
        key="endpoints",
        name="Running Containers",
        icon="mdi:truck-cargo-container",
        entity_category=None,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="RunningContainerCount",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        data_attributes_list=DEVICE_ATTRIBUTES_ENDPOINTS,
        func="EndpointSensor",
    ),
    PortainerSensorEntityDescription(
        key="containers",
        name="State",
        icon="mdi:docker",
        entity_category=None,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="State",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        data_attributes_list=DEVICE_ATTRIBUTES_CONTAINERS,
        func="ContainerSensor",
    ),
)

SENSOR_TYPES_FEATURES: tuple[PortainerSensorEntityDescription, ...] = (
    PortainerSensorEntityDescription(
        key="container_health",
        name="Health",
        icon="mdi:heart-pulse",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Health_Status",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_created",
        name="Created",
        icon="mdi:clock-start",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Created",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_ip_address",
        name="IP Address",
        icon="mdi:ip-network",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="IPAddress",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=True,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_published_ports",
        name="Published Ports",
        icon="mdi:lan-connect",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="PublishedPorts",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=True,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_restart_policy",
        name="Restart Policy",
        icon="mdi:restart-alert",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Restart_Policy",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_mounts",
        name="Mounts",
        icon="mdi:harddisk",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Mounts",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_started_at",
        name="Last Start",
        icon="mdi:play-circle-outline",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="StartedAt",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=True,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_image_id",
        name="Image ID",
        icon="mdi:pound-box",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="ImageID",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_network_mode",
        name="Network Mode",
        icon="mdi:network-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Network",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_exit_code",
        name="Exit Code",
        icon="mdi:exit-run",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="ExitCode",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        supported_states=["exited"],
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_privileged_mode",
        name="Privileged Mode",
        icon="mdi:security",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Privileged",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_compose_stack",
        name="Compose Stack",
        icon="mdi:stack-overflow",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Compose_Stack",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="container_compose_service",
        name="Compose Service",
        icon="mdi:stack-overflow",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="data__EndpointId",
        data_path="containers",
        data_attribute="Compose_Service",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="ContainerSensor",
    ),
    PortainerSensorEntityDescription(
        key="endpoint_unhealthy_containers",
        name="Unhealthy Containers",
        icon="mdi:alert-circle",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="UnhealthyContainerCount",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        func="EndpointSensor",
    ),
    PortainerSensorEntityDescription(
        key="endpoint_stopped_containers",
        name="Stopped Containers",
        icon="mdi:stop-circle",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="StoppedContainerCount",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        func="EndpointSensor",
    ),
    PortainerSensorEntityDescription(
        key="endpoint_total_images",
        name="Total Images",
        icon="mdi:image-multiple",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="ImageCount",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        func="EndpointSensor",
    ),
    PortainerSensorEntityDescription(
        key="endpoint_total_volumes",
        name="Total Volumes",
        icon="mdi:harddisk",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="VolumeCount",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        func="EndpointSensor",
    ),
    PortainerSensorEntityDescription(
        key="endpoint_total_stacks",
        name="Total Stacks",
        icon="mdi:stack-overflow",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="StackCount",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        func="EndpointSensor",
    ),
    PortainerSensorEntityDescription(
        key="endpoint_reachable",
        name="Reachable",
        icon="mdi:check-network",
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="Endpoints",
        data_path="endpoints",
        data_attribute="Status",
        data_name="Name",
        data_uid="",
        data_reference="Id",
        entity_registry_enabled_default=False,
        func="EndpointSensor",
    ),
)

SENSOR_SERVICES = []
